### ISSUE TITLE
Runtime Logs disappear if idling on logs page

### ISSUE THREAD

**Issue by denolfe** [payloadcms/website#185] opened 2023-06-22 15:56 UTC
On a project, go to runtime logs. Wait a few minutes, the logs will disappear after some time. You have to refresh to see them again.

<img width="1527" alt="CleanShot 2023-06-22 at 11 55 31@2x" src="https://github.com/payloadcms/website/assets/65888/b2286db4-a072-4883-b3f3-f441c27f04f2">

**Comment by JarrodMFlesch** [comment] 2023-08-29 17:56
Could not reproduce. I see this was added a while ago so I am closing for now.

**Comment by jacobsfletch** [comment] 2023-08-29 18:09
@JarrodMFlesch I am able to reproduce pretty consistently in production

**Closed** 2023-08-30 20:51 UTC
Labels: bug
